ALTER TABLE sensor
    ADD COLUMN exhaust BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX idx_sensor_created_at ON sensor (created_at);

CREATE TABLE actuator_state (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    device_id VARCHAR(100) NOT NULL UNIQUE,
    heater BOOLEAN NOT NULL DEFAULT FALSE,
    kipas BOOLEAN NOT NULL DEFAULT FALSE,
    exhaust BOOLEAN NOT NULL DEFAULT FALSE,
    mode VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    updated_at DATETIME NOT NULL
);
